CREATE TABLE
  Personas (
    PersonaID INT IDENTITY (1, 1) PRIMARY KEY,
    UUId UNIQUEIDENTIFIER DEFAULT NEWID (),
    FechaRegistro DATETIME DEFAULT GETDATE (),
    FechaActualizacion DATETIME DEFAULT GETDATE (),
    DOB DATE, -- Fecha de nacimiento
    DOD DATE, -- Fecha de fallecimiento
    Pais VARCHAR(64),
    NumCI VARCHAR(16),
    OrigenCI VARCHAR(16),
    ExtensionCI VARCHAR(16),
    Ocupacion VARCHAR(128),
    Migrante BIT,
    RequiereInterprete BIT,
    TratamientoPersonal VARCHAR(16),
    PrimerNombre VARCHAR(64),
    SegundoNombre VARCHAR(64),
    ApellidoPaterno VARCHAR(64),
    ApellidoMaterno VARCHAR(64),
    ComunicacionPreferida VARCHAR(16),
    IdiomaPrincipal VARCHAR(64),
    IdiomaSecundario VARCHAR(64),
    NumCelular VARCHAR(16),
    CorreoElectronico VARCHAR(128),
    CorreoPrivado VARCHAR(128),
    Genero VARCHAR(16),
    EstadoCivil VARCHAR(16),
    Religion VARCHAR(64),
    Etnia VARCHAR(64),
    NumSeguroSocial VARCHAR(32),
    Estado BIT,
    RazonEstado VARCHAR(128),
    FechaEstado DATETIME DEFAULT GETDATE (),
  );